.PHONY: mock
mock:
	@mockgen -source=/Users/moocss/gowork/pkg/mod/github.com/redis/go-redis/v9@v9.2.1/commands.go -package=redismocks -destination=/Users/moocss/work/GoProjects/sea-kit/ginx/internal/mocks/cmd.mock.go
	@go mod tidy